<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
}
$searchAction = "/s/yorubadiaspora/item";
$searchValue = $this->escapeHtml($this->params()->fromQuery('property[0][text]', ''));
?>

<form action="<?php echo $this->escapeHtml($searchAction); ?>" id="search-form">
    <input type="text" name="property[0][text]" value="<?php echo $searchValue; ?>"
        placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>">
    <input type="hidden" name="property[0][joiner]" value="and" />
    <input type="hidden" name="property[0][property]" value="" />
    <input type="hidden" name="property[0][type]" value="in" />
    <input type="hidden" name="resource_template_id[]" value="5" />
    <button type="submit"><?php echo $translate('Search'); ?></button>
</form>
