<?php echo $this->pageTitle(sprintf($this->translate('Search results for “%s”'), $query)); ?>
<div>
    <h2><?php echo $this->translate('Pages'); ?></h2>
    <?php if ($pages): ?>
    <ul>
        <?php foreach ($pages as $page): ?>
        <li><?php echo $page->link($page->title()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results (%s total)'), $pagesTotal),
        $this->url(
            'site/page-browse',
            ['controller' => 'page', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No pages found'); ?></p>
    <?php endif; ?>
</div>
